export const GET_TRANSACTION_LIST = 'GET_TRANSACTION_LIST';
export const GET_TRANSACTION_LIST_SUCCESS = 'GET_TRANSACTION_LIST_SUCCESS';
export const GET_TRANSACTION_LIST_FAILED = 'GET_TRANSACTION_LIST_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_TRAN = 'EXPORT_EXCEL_FILE_REPORT_TRAN';
export const EXPORT_EXCEL_FILE_REPORT_TRAN_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_TRAN_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_TRAN_FAILED = 'EXPORT_EXCEL_FILE_REPORT_TRAN_FAILED';

export const GET_TRANSACTION_DETAIL = 'GET_TRANSACTION_DETAIL';
export const GET_TRANSACTION_DETAIL_SUCCESS = 'GET_TRANSACTION_DETAIL_SUCCESS';
export const GET_TRANSACTION_DETAIL_FAILED = 'GET_TRANSACTION_DETAIL_FAILED';

export const GET_TRANSACTION_DETAIL_REFUND = 'GET_TRANSACTION_DETAIL_REFUND';
export const GET_TRANSACTION_DETAIL_REFUND_SUCCESS = 'GET_TRANSACTION_DETAIL_REFUND_SUCCESS';
export const GET_TRANSACTION_DETAIL_REFUND_FAILED = 'GET_TRANSACTION_DETAIL_REFUND_FAILED';

export const GET_TRANSACTION_LIST_REFUND = 'GET_TRANSACTION_LIST_REFUND';
export const GET_TRANSACTION_LIST_REFUND_SUCCESS = 'GET_TRANSACTION_LIST_REFUND_SUCCESS';
export const GET_TRANSACTION_LIST_REFUND_FAILED = 'GET_TRANSACTION_LIST_REFUND_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_TRAN_REFUND = 'EXPORT_EXCEL_FILE_REPORT_TRAN_REFUND';
export const EXPORT_EXCEL_FILE_REPORT_TRAN_REFUND_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_TRAN_REFUND_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_TRAN_REFUND_FAILED = 'EXPORT_EXCEL_FILE_REPORT_TRAN_REFUND_FAILED';

export const CREATE_TRANSACTION_REFUND = 'CREATE_TRANSACTION_REFUND';
export const CREATE_TRANSACTION_REFUND_SUCCESS = 'CREATE_TRANSACTION_REFUND_SUCCESS';
export const CREATE_TRANSACTION_REFUND_FAILED = 'CREATE_TRANSACTION_REFUND_FAILED';

export const UPDATE_TRANSACTION_STATUS = 'UPDATE_TRANSACTION_STATUS';
export const UPDATE_TRANSACTION_STATUS_SUCCESS = 'UPDATE_TRANSACTION_STATUS_SUCCESS';
export const UPDATE_TRANSACTION_STATUS_FAILED = 'UPDATE_TRANSACTION_STATUS_FAILED';

export const UPDATE_TRANSACTION_REFUND_STATUS = 'UPDATE_TRANSACTION_REFUND_STATUS';
export const UPDATE_TRANSACTION_REFUND_STATUS_SUCCESS = 'UPDATE_TRANSACTION_REFUND_STATUS_SUCCESS';
export const UPDATE_TRANSACTION_REFUND_STATUS_FAILED = 'UPDATE_TRANSACTION_REFUND_STATUS_FAILED';
