const validateField = {
  isRequiredInput: 'Vui lòng nhập',
  isRequiredSelect: 'Vui lòng chọn',
  isValid: 'Giá trị không hợp lệ.',
  isValidField: 'không hợp lệ',
  checkEmailFormat: ' không đúng định dạng ',
  checkPhoneNumber: 'Số điện thoại không đúng định dạng.',
  checkUnique: 'đã tồn tại trong hệ thống. Vui lòng kiểm tra lại.',
  taxCodeLabel: 'trước khi lấy thông tin tài khoản thụ hưởng',
  checkContainSpace: 'không chứa khoảng trắng',
  containSpecialCharacters: 'không chứa ký tự đặc biệt',
  checkCharacerFormat: 'bắt buộc phải có ký tự số, ký tự chữ và ký tự đặc biệt',
  numberAndCharRequired: 'bắt buộc phải có ký tự số, ký tự chữ',
  notVietnamese: 'không nhập tiếng việt có dấu',
  isNumber: 'Phải là số',
  isCode: ' chỉ cho phép nhập ký tự chữ, tiếng việt không dấu, hoặc số',
  notFormatNumber: 'không được phép nhập số',
  isLength8: 'không dài hơn 8 ký tự.',
  isLength10: 'không dài hơn 10 ký tự.',
  isLength13: 'không dài hơn 13 ký tự.',
  isLength19: 'không dài hơn 19 ký tự.',
  isLength20: 'không dài hơn 20 ký tự.',
  isLength25: 'không dài hơn 25 ký tự.',
  isLength30: 'không dài hơn 30 ký tự.',
  isLength50: 'không dài hơn 50 ký tự.',
  isLength28: 'độ dài trong khoảng từ 2 đến 8 ký tự.',
  isLength450: 'độ dài trong khoảng từ 4 đến 50 ký tự.',
  isLength3150: 'độ dài trong khoảng từ 3 đến 150 ký tự.',
  isLength350: 'độ dài trong khoảng từ 3 đến 50 ký tự.',
  isLength314: 'độ dài trong khoảng từ 3 đến 14 ký tự.',
  isLength1013: 'độ dài trong khoảng từ 10 đến 13 ký tự.',
  isLength650: 'độ dài trong khoảng từ 6 đến 50 ký tự.',
  isLength6150: 'độ dài trong khoảng từ 6 đến 150 ký tự.',
  isLength620: 'độ dài trong khoảng từ 6 đến 20 ký tự.',
  isLength680: 'độ dài trong khoảng từ 6 đến 80 ký tự.',
  isLength10150: 'độ dài trong khoảng từ 10 đến 150 ký tự.',
  isLength100: 'không dài hơn 100 ký tự.',
  isLength150: 'không dài hơn 150 ký tự.',
  isLength200: 'không dài hơn 200 ký tự.',
  formatImage: 'Định dạng ảnh chỉ cho phép .png|.jpg|.jpeg',
};

export default validateField;
