const MnMerchant = {
  merchantId: 'Merchant ID',
  titleAddMerchant: 'Thêm mới Merchant',
  titleEditMerchant: 'Cập nhật thông tin Merchant',
  businessInfo: 'Thông tin kinh doanh',
  merchantName: 'Tên Merchant',
  shortName: 'Tên viết tắt',
  masterMerchant: 'Master Merchant',
  supplierCode: 'Mã nhà cung cấp (Billing)',
  nationalMCC: 'MCC quốc tế',
  registeredBusinessAddress: 'Địa chỉ đăng ký kinh doanh',
  businessAddress: 'Địa chỉ kinh doanh',
  city: 'Tỉnh / Thành phố',
  district: 'Quận / Huyện',
  zipCode: 'Mã bưu điện',
  taxCode: 'Mã số thuế / CMND',
  website: 'Website (Doanh nghiệp)',
  attachments: 'Tài liệu đính kèm',
  businessLicence: 'Giấy phép đăng ký kinh doanh',
  domainLicence: 'Giấy phép đăng ký tên miền',
  identityCard: 'CMND/ Thẻ căn cước công dân',
  accountLicence: 'Giấy phép đăng ký tài khoản với cơ quan thuế',
  contractSign: 'Ký kết hợp đồng',
  agentDevelopmentBranch: 'Chi nhánh phát triển đại lý',
  developmentUnit: 'Đơn vị phát triển',
  staff: 'Nhân viên',
  merchantBranchInfo: 'Thông tin chi nhánh Merchant',
  terminalID: 'Terminal ID',
  terminalName: 'Tên Terminal',
  websiteEcommerce: 'Website (TMĐT)',
  inlandMCC: 'MCC nội địa',
  userName: 'Tên đăng nhập',
  terminalInfo: 'Thông tin Terminal điểm bán',
  terminalTitle: 'Thông tin Terminal',
  serviceCode: 'Mã dịch vụ (Billing)',
  productBusinessDesciption: 'Mô tả thêm sản phẩm kinh doanh',
  facebook: 'Facebook',
  beneficiaryAccount: 'Tài khoản thụ hưởng',
  accountNumber: 'Số tài khoản',
  accountOwn: 'Chủ tài khoản',
  bank: 'Ngân hàng',
  branch: 'Chi nhánh',
  currency: 'Loại tiền',
  contactInfo: 'Thông tin liên hệ',
  fullName: 'Họ tên',
  phoneNumber: 'Số điện thoại',
  email: 'Email',
  visaPan: 'Visa pan',
  masterCartPan: 'MasterCart pan',
  jCBPan: 'JCB pan',
  notification: 'Nhận tin thông báo',
  sms: 'SMS',
  ott: 'OTT',
  short: 'viết tắt',
  address: 'Địa chỉ',
  contact: 'Người liên hệ',
  iniDate: 'Ngày khởi tạo',
  deniedDate: 'Ngày từ chối',
  status: 'Trạng thái',
  mcBranch: 'Chi nhánh Merchant',
  terminalPlace: 'Điểm bán',
  rank: 'Cấp bậc',
  processUser: 'Người xử lý',
  reason: 'Lý do',
  errorCode: 'Mã lỗi',
};

const MnTerminal = {
  level: 'Cấp bậc',
  titleAddTerminal: 'Thêm mới Terminal',
  titleInfoTerminal: 'Chi nhánh Merchant',
  branch: 'Chi nhánh',
  pointSale: 'Điểm bán',
  terminalDetail: 'Thông tin Terminal',
};

const btnMerchant = {
  comeBackList: 'Về danh sách',
  save: 'Lưu',
  update: 'Cập nhật',
  submitApprove: 'Gửi duyệt',
};

const MerchantList = {
  merchantList: 'Danh sách Merchant',
  applyDate: 'Từ ngày',
  expireDate: 'Đến ngày',
};

const MerchantDetail = {
  print: 'IN',
  titleUnitBusinessInfo: 'Thông tin đơn vị kinh doanh',
  mcInfo: 'Thông tin merchant',
  mcId: 'Merchant ID',
  mcName: 'Tên Merchant',
  abbreviationName: 'Tên Viết Tắt',
  masterMerchant: 'Master Merchant',
  billingCode: 'Mã Nhà Cung Cấp',
  mccInternational: 'MCC Quốc Tế',
  addressBusinessRegister: 'Địa Chỉ Đăng Kí Kinh Doanh',
  addressBusiness: 'Địa Chỉ Kinh Doanh',
  province: 'Tỉnh/Thành Phố',
  district: 'Quận/Huyện',
  zipCode: 'Mã Bưu Điện',
  taxCode: 'Mã Số Thuế/CMND',
  webSite: 'Website(Doanh nghiệp)',
  status: 'Trạng Thái',
  businessLicence: 'Giấy phép đăng ký kinh doanh',
  domainLicence: 'Giấy phép đăng ký tên miền',
  accountLicence: 'Giấy phép đăng ký tài khoản với cơ quan thuế',
  contractSign: 'Hợp đồng kí kết',
  identityCard: 'CMND/ Thẻ căn cước công dân',
  accountMerchantWebAndApp: 'Tài khoản đăng nhập Merchant Web và Merchant App',
  accountTerminalWebAndApp: 'Tài khoản đăng nhập Terminal Web và Terminal App',
  accountMerchant: 'Tên đăng nhập',
  agentDevelopmentBranch: 'Chi nhánh phát triển đại lý',
  developmentUnit: 'Đơn vị phát triển',
  staff: 'Nhân viên',
  stt: 'STT',
  terminalID: 'Terminal ID',
  purpose: 'Mục đích',
  terminalName: 'Tên Terminal',
  rank: 'Cấp Bậc',
  registerDate: 'Ngày đăng kí',
  approveOrDeniedDate: 'Ngày duyệt/Từ chối',
  organizationInternationalContact: 'Thông tin tổ chức quốc tế',
  organization: 'Tổ chức',
  denied: 'Từ chối',
  approved: 'Duyệt',
  action: 'Thao tác',
  arrayDenied: [
    {
      code: '1',
      description: 'Thông tin không đúng',
    },
    {
      code: '2',
      description: 'Thiếu thông tin',
    },
    {
      code: '3',
      description: 'Sản phẩm phạm pháp',
    },
    {
      code: '4',
      description: 'Sản phẩm không đủ điều kiện đăng ký',
    },
    {
      code: '5',
      description: 'Khác',
    },
  ],
};

const QRCode = {
  createQRCode: 'Tạo QRCode',
  cancel: 'Hủy',
  titleAddQRCode: 'TẠO QRCODE SẢN PHẨM',
  pointSale: 'Mã điểm bán - Tên điểm bán',
  productCode: 'Mã sản phẩm',
  productName: 'Tên sản phầm',
  productPrice: 'Giá sản phẩm',
  productNote: 'Ghi chú',
  expireQRCode: 'Thời hạn QrCode',
  productImage: 'Hình ảnh',
  titleCreateResult: 'Kết quả được tạo',
  qrSave: 'Lưu ảnh QR về máy',
  sendEmail: 'Gửi Email',
  printQRCode: 'In ảnh QrCode',
  fieldName: 'Tên trường',
  tag: 'Tag',
  valueName: 'Tên giá trị',
  valueTag: 'Tag Value',
  data: 'Dữ liệu',
  dataVersion: 'Phiên bản dữ liệu',
  initializationMethod: 'Phương thức khởi tạo',
  visaPan: 'Visa Pan',
  masterCardPan: 'MasterCard Pan',
  jcbPan: 'JCB Pan',
  indentifyMechant: 'Định danh Merchant',
  catalogCodeMerchant: 'Mã danh mục Merchant',
  currencyCode: 'Mã tiền tệ',
  transactionAmount: 'Số tiền giao dịch',
  countryCode: 'Mã quốc gia',
  merchantName: 'Tên Merchant',
  city: 'Thành phố',
  zipCode: 'Mã bưu điện',
  additionalInfo: 'Thông tin bổ sung',
  goBack: 'Quay về',
  vietinbankQrPay: ' Vietinbank QRPAY',
  titleQRCodeList: 'Danh sách QRCode sản phẩm',
  pointSaleCode: 'Mã điểm bán',
  pointSaleName: 'Tên điểm bán',
  titleEditQRCode: 'Chỉnh sửa thông tin QRCode',
  infoInternational: 'Thông tin quốc tế',
  createTime: 'Thời gian tạo',
};

const StatisticalReport = {
  transactionCode: 'Mã giao dịch',
  billNumber: 'Số hóa đơn',
  merchantBranch: 'Tên chi nhánh Merchant',
  merchantCode: 'Mã chi nhánh Merchant',
  ttUnit: 'Đơn vị TT',
  ttType: 'Loại TT',
  kmBeforeMoney: 'Số tiền trước km',
  kmAfterMoney: 'Số tiền sau km',
  ttTime: 'Thời gian TT',
  reportDetailTransactionSuccess: 'Báo báo chi tiết giao dịch thành công',
  reportDetailTransactionUpdate: 'Báo báo chi tiết giao dịch thành công phát sinh',
  transactionFail: 'Báo báo chi tiết giao dịch lỗi',
  paymentType: 'Loại thanh toán',
  paymentUnit: 'Đơn vị thanh toán',
  status: 'Trạng thái',
  reportDetailTransactionInterMcc: 'Báo báo tổng hợp doanh số theo MCC quốc tế',
  internationalMccName: 'Tên MCC quốc tế',
  internationalMcc: 'MCC quốc tế',
  midTotal: 'Tổng MID',
  tidTotal: 'Tổng Tid',
  transactionTotal: 'Tổng số lượng GD',
  salesTotal: 'Tổng doanh số',
  amountTotal: 'Tổng tiền',
  mid: 'Mid',
  tid: 'Tid',
  transactions: 'Số lượng GD',
  sales: 'Doanh số',
  reportDetailTransactionMmc: 'Báo cáo tổng hợp doanh số theo đơn vị hợp tác',
  reportDetailTransactionRefund: 'Báo cáo chi tiết giao dịch hoàn tiền',
  tranCodeRoot: 'Mã GD gốc',
  tranCodeRefund: 'Mã GD hoàn',
  payAmount: 'Số tiền yêu cầu hoàn',
  payRefund: 'Số tiền hoàn thực',
  payDate: 'Ngày thanh toán',
  amount: 'Số lượng',
  reportDetailTransactionMerchant: 'Báo cáo tổng hợp doanh số theo Merchant',
  reportDetailTransactionMerchantBranch: 'Báo cáo tổng hợp doanh số theo chi nhánh Merchant',
  updateTimeTransaction: 'Thời gian cập nhật GD',
};

export default {
  MnMerchant,
  MnTerminal,
  btnMerchant,
  MerchantDetail,
  MerchantList,
  QRCode,
  StatisticalReport,
};
