const MnMerchant = {
  merchantId: 'Merchant ID',
  titleAddMerchant: 'Thêm mới Merchant',
  titleEditMerchant: 'Cập nhật thông tin Merchant',
  businessInfo: 'Thông tin kinh doanh',
  merchantName: 'Tên Merchant',
  shortName: 'Tên viết tắt',
  masterMerchant: 'Master Merchant',
  supplierCode: 'Mã nhà cung cấp (Billing)',
  nationalMCC: 'MCC quốc tế',
  registeredBusinessAddress: 'Địa chỉ đăng ký kinh doanh',
  businessAddress: 'Địa chỉ kinh doanh',
  city: 'Tỉnh / Thành phố',
  district: 'Quận / Huyện',
  zipCode: 'Mã bưu điện',
  taxCode: 'Mã số thuế / CMND',
  website: 'Website (Doanh nghiệp)',
  attachments: 'Tài liệu đính kèm',
  businessLicence: 'Giấy phép đăng ký kinh doanh',
  domainLicence: 'Giấy phép đăng ký tên miền',
  identityCard: 'CMND/ Thẻ căn cước công dân',
  accountLicence: 'Giấy phép đăng ký tài khoản với cơ quan thuế',
  contractSign: 'Ký kết hợp đồng',
  agentDevelopmentBranch: 'Chi nhánh phát triển đại lý',
  developmentUnit: 'Đơn vị phát triển',
  staff: 'Nhân viên',
  merchantBranchInfo: 'Thông tin chi nhánh Merchant',
  terminalID: 'Terminal ID',
  terminalName: 'Tên Terminal',
  websiteEcommerce: 'Website (TMĐT)',
  inlandMCC: 'MCC nội địa',
  userName: 'Tên đăng nhập',
  terminalInfo: 'Thông tin điểm bán',
  serviceCode: 'Mã dịch vụ (Billing)',
  productBusinessDesciption: 'Mô tả thêm sản phẩm kinh doanh',
  facebook: 'Facebook',
  beneficiaryAccount: 'Tài khoản thụ hưởng',
  accountNumber: 'Số tài khoản',
  accountOwn: 'Chủ tài khoản',
  bank: 'Ngân hàng',
  branch: 'Chi nhánh',
  currency: 'Loại tiền tệ',
  contactInfo: 'Thông tin liên hệ',
  fullName: 'Họ tên',
  phoneNumber: 'Số điện thoại',
  email: 'Email',
  notification: 'Nhận tin thông báo',
  sms: 'SMS',
  ott: 'OTT',
  short: 'viết tắt',
  address: 'Địa chỉ',
  contact: 'Người liên hệ',
  iniDate: 'Ngày khởi tạo',
  status: 'Trạng thái',
  processDate: 'Ngày xử lý',
  deniedUser: 'Người từ chối',
  reason: 'Lý do',
  visaPan: 'Visa pan',
  masterCartPan: 'MasterCart pan',
  jCBPan: 'JCB pan',
  reasonReject: 'Lý do từ chối',
  content: 'Nội dung',
  dateTime: 'Thời gian',
};

const btnMerchant = {
  comeBackList: 'Về danh sách',
  save: 'Lưu',
  submitApprove: 'Gửi duyệt',
};

const MerchantList = {
  merchantList: 'Danh sách Merchant',
  merchantListPending: 'Danh sách Merchant chờ duyệt',
  historyMerchantListDenied: 'Lịch sử danh sách Merchant từ chối',
  merchantListDenied: 'Danh sách Merchant từ chối',
  applyDate: 'Từ ngày',
  expireDate: 'Đến ngày',
  enjoymentInfo: 'Thông tin thụ hưởng',
  enjoymentAccountNumber: 'Số tài khoản thụ hưởng',
  enjoymentAccountOwn: 'Chủ tài khoản thụ hưởng',
  enjoymentBank: 'Ngân hàng thụ hưởng',
  enjoymentBranch: 'Chi nhánh thụ hưởng',
  contactInfo: 'Thông tin người liên hệ',
  contactFullName: 'Họ tên người liên hệ ',
  contactPhoneNumber: 'Số điện thoại liên hệ',
  contactEmail: 'Email liên hệ',
};

const MerchantDetail = {
  print: 'IN',
  titleUnitBusinessInfo: 'Thông tin đơn vị kinh doanh',
  mcInfo: 'Thông tin merchant',
  mcId: 'Merchant ID',
  mcName: 'Tên Merchant',
  abbreviationName: 'Tên Viết Tắt',
  masterMerchant: 'Master Merchant',
  billingCode: 'Mã Nhà Cung Cấp(Billing)',
  mccInternational: 'MCC Quốc Tế',
  addressBusinessRegister: 'Địa Chỉ Đăng Kí Kinh Doanh',
  addressBusiness: 'Địa Chỉ Kinh Doanh',
  province: 'Tỉnh/Thành Phố',
  district: 'Quận/Huyện',
  zipCode: 'Mã Bưu Điện',
  taxCode: 'Mã Số Thuế/CMND',
  webSite: 'Website(Doanh nghiệp)',
  status: 'Trạng Thái',
  businessLicence: 'Giấy phép đăng ký kinh doanh',
  domainLicence: 'Giấy phép đăng ký tên miền',
  accountLicence: 'Giấy phép đăng ký tài khoản với cơ quan thuế',
  contractSign: 'Hợp đồng kí kết',
  identityCard: 'CMND/ Thẻ căn cước công dân',
  accountMerchantWebAndApp: 'Tài khoản đăng nhập Merchant Web và Merchant App',
  accountMerchant: 'Tên đăng nhập',
  agentDevelopmentBranch: 'Chi nhánh phát triển đại lý',
  developmentUnit: 'Đơn vị phát triển',
  staff: 'Nhân viên',
  stt: 'STT',
  terminalID: 'Terminal ID',
  terminalName: 'Tên Terminal',
  merchantBranch: 'Chi nhánh Merchant',
  rank: 'Cấp Bậc',
  registerDate: 'Ngày đăng kí',
  approveOrDeniedDate: 'Ngày duyệt/Từ chối',
  organizationInternationalContact: 'Thông tin tổ chức quốc tế',
  organization: 'Tổ chức',
  denied: 'Từ chối',
  approved: 'Duyệt',
  action: 'Thao tác',
  arrayDenied: [
    {
      code: '1',
      description: 'Thông tin không đúng',
    },
    {
      code: '2',
      description: 'Thiếu thông tin',
    },
    {
      code: '3',
      description: 'Sản phẩm phạm pháp',
    },
    {
      code: '4',
      description: 'Sản phẩm không đủ điều kiện đăng ký',
    },
    {
      code: '5',
      description: 'Khác',
    },
  ],
};

export default {
  MnMerchant,
  btnMerchant,
  MerchantDetail,
  MerchantList,
};
