export const LOAD_DEFAULT_DATA_STAFF = 'LOAD_DEFAULT_DATA_STAFF';

export const LOAD_DEFAULT_DATA_STAFF_SUCCESS = 'LOAD_DEFAULT_DATA_STAFF_SUCCESS';

export const LOAD_DEFAULT_DATA_STAFF_FAIL = 'LOAD_DEFAULT_DATA_STAFF_FAIL';


export const SEARCH_BY_PAGINATION = 'SEARCH_BY_CURRENT_PAGE';

export const SEARCH_BY_PAGINATION_SUCCESS = 'SEARCH_BY_PAGINATION_SUCCESS';

export const SEARCH_BY_PAGINATION_FAIL = 'SEARCH_BY_PAGINATION_FAIL';


export const CLICK_TO_OPEN_STAFF_MODAL = 'CLICK_TO_OPEN_STAFF_MODAL';

export const CLICK_TO_CLOSE_STAFF_MODAL = 'CLICK_TO_CLOSE_STAFF_MODAL';

export const CHANGE_STATUS_STAFF = 'CHANGE_STATUS_STAFF';

export const CHANGE_STATUS_STAFF_SUCCESS = 'CHANGE_STATUS_STAFF_SUCCESS';

export const CHANGE_STATUS_STAFF_FAIL = 'CHANGE_STATUS_STAFF_FAIL';

