export const GET_INFO_STAFF = 'GET_INFO_STAFF';

export const GET_INFO_STAFF_SUCCESS = 'GET_INFO_STAFF_SUCCESS';

export const GET_INFO_STAFF_FAIL = 'GET_INFO_STAFF';

export const UPDATE_INFO_STAFF = 'UPDATE_INFO_STAFF';

export const UPDATE_INFO_STAFF_SUCCESS = 'UPDATE_INFO_STAFF_SUCCESS';

export const UPDATE_INFO_STAFF_FAIL = 'UPDATE_INFO_STAFF_FAIL';

