export const ADD_MASTER_MERCHANT = 'ADD_MASTER_MERCHANT';
export const ADD_MASTER_MERCHANT_SUCCESS = 'ADD_MASTER_MERCHANT_SUCCESS';
export const ADD_MASTER_MERCHANT_FAILED = 'ADD_MASTER_MERCHANT_FAILED';

export const GET_MERCHANT_DETAIL = 'GET_MERCHANT_DETAIL';
export const GET_MERCHANT_DETAIL_SUCCESS = 'GET_MERCHANT_DETAIL_SUCCESS';
export const GET_MERCHANT_DETAIL_FAILED = 'GET_MERCHANT_DETAIL_FAILED';

export const GET_MERCHANT_CODE_NAME = 'GET_MERCHANT_CODE_NAME';
export const GET_MERCHANT_CODE_NAME_SUCCESS = 'GET_MERCHANT_CODE_NAME_SUCCESS';
export const GET_MERCHANT_CODE_NAME_FAILED = 'GET_MERCHANT_CODE_NAME_FAILED';

export const GET_LIST_TERMINAL_DETAIL = 'GET_LIST_TERMINAL_DETAIL';
export const GET_LIST_TERMINAL_DETAIL_SUCCESS = 'GET_LIST_TERMINAL_DETAIL_SUCCESS';
export const GET_LIST_TERMINAL_DETAIL_FAILED = 'GET_LIST_TERMINAL_DETAIL_FAILED';

export const GET_MERCHANT_LIST = 'GET_MERCHANT_LIST';
export const GET_MERCHANT_LIST_SUCCESS = 'GET_MERCHANT_LIST_SUCCESS';
export const GET_MERCHANT_LIST_FAILED = 'GET_MERCHANT_LIST_FAILED';

export const GET_MERCHANT_LIST_DENIED = 'GET_MERCHANT_LIST_DENIED';
export const GET_MERCHANT_LIST_DENIED_SUCCESS = 'GET_MERCHANT_LIST_DENIED_SUCCESS';
export const GET_MERCHANT_LIST_DENIED_FAILED = 'GET_MERCHANT_LIST_DENIED_FAILED';

export const GET_MERCHANT_INFO = 'GET_MERCHANT_INFO';
export const GET_MERCHANT_INFO_SUCCESS = 'GET_MERCHANT_INFO_SUCCESS';
export const GET_MERCHANT_INFO_FAILED = 'GET_MERCHANT_INFO_FAILED';

export const APPROVED_MERCHANT = 'APPROVED_MERCHANT';
export const APPROVED_MERCHANT_SUCCESS = 'APPROVED_MERCHANT_SUCCESS';
export const APPROVED_MERCHANT_FAILED = 'APPROVED_MERCHANT_FAILED';

export const DENIED_MERCHANT = 'DENIED_MERCHANT';
export const DENIED_MERCHANT_SUCCESS = 'DENIED_MERCHANT_SUCCESS';
export const DENIED_MERCHANT_FAILED = 'DENIED_MERCHANT_FAILED';

export const UPDATE_MERCHANT = 'UPDATE_MERCHANT';
export const UPDATE_MERCHANT_SUCCESS = 'UPDATE_MERCHANT_SUCCESS';
export const UPDATE_MERCHANT_FAILED = 'UPDATE_MERCHANT_FAILED';

export const CLICK_OPEN_LOCK_MODAL = 'CLICK_OPEN_LOCK_MODAL';
export const CLICK_CLOSE_LOCK_MODAL = 'CLICK_CLOSE_LOCK_MODAL';

export const CLICK_OPEN_UN_LOCK_MODAL = 'CLICK_OPEN_UN_LOCK_MODAL';
export const CLICK_CLOSE_UN_LOCK_MODAL = 'CLICK_CLOSE_UN_LOCK_MODAL';

export const LOCK_UNLOCK_MERCHANT = 'LOCK_UNLOCK_MERCHANT';
export const LOCK_UNLOCK_MERCHANT_SUCCESS = 'LOCK_UNLOCK_MERCHANT_SUCCESS';
export const LOCK_UNLOCK_MERCHANT_FAILED = 'LOCK_UNLOCK_MERCHANT_FAILED';

export const CLICK_TO_CHANGE_STATUS_IN_LOCK_MODAL = 'CLICK_TO_CHANGE_STATUS_IN_LOCK_MODAL';
export const CLICK_TO_CHANGE_STATUS_IN_LOCK_MODAL_SUCCESS = 'CLICK_TO_CHANGE_STATUS_IN_LOCK_MODAL_SUCCESS';
export const CLICK_TO_CHANGE_STATUS_IN_LOCK_MODAL_FAILED = 'CLICK_TO_CHANGE_STATUS_IN_LOCK_MODAL_FAILED';

export const CLICK_TO_CHANGE_STATUS_IN_UN_LOCK_MODAL = 'CLICK_TO_CHANGE_STATUS_IN_UN_LOCK_MODAL';
export const CLICK_TO_CHANGE_STATUS_IN_UN_LOCK_MODAL_SUCCESS = 'CLICK_TO_CHANGE_STATUS_IN_UN_LOCK_MODAL_SUCCESS';
export const CLICK_TO_CHANGE_STATUS_IN_UN_LOCK_MODAL_FAILED = 'CLICK_TO_CHANGE_STATUS_IN_UN_LOCK_MODAL_FAILED';

export const EXPORT_EXCEL_FILE = 'EXPORT_EXCEL_FILE';
export const EXPORT_EXCEL_FILE_SUCCESS = 'EXPORT_EXCEL_FILE_SUCCESS';
export const EXPORT_EXCEL_FILE_FAILED = 'EXPORT_EXCEL_FILE_FAILED';

export const CLEAR_MERCHANT_DETAIL = 'CLEAR_MERCHANT_DETAIL';

export const GET_MERCHANT_DETAIL_DENIED = 'GET_MERCHANT_DETAIL_DENIED';
export const GET_MERCHANT_DETAIL_DENIED_SUCCESS = 'GET_MERCHANT_DETAIL_DENIED_SUCCESS';
export const GET_MERCHANT_DETAIL_DENIED_FAILED = 'GET_MERCHANT_DETAIL_DENIED_FAILED';

export const CLEAR_MERCHANT_CODE_NAME = 'CLEAR_MERCHANT_CODE_NAME';
