export const ADD_MID_TID = 'ADD_MID_TID';
export const ADD_MID_TID_SUCCESS = 'ADD_MID_TID_SUCCESS';
export const ADD_MID_TID_FAILED = 'ADD_MID_TID_FAILED';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILED = 'GET_USER_INFO_FAILED';

export const EDIT_MID_TID = 'EDIT_MID_TID';
export const EDIT_MID_TID_SUCCESS = 'EDIT_MID_TID_SUCCESS';
export const EDIT_MID_TID_FAILED = 'EDIT_MID_TID_FAILED';

export const GET_MID_TID_LIST = 'GET_MID_TID_LIST';
export const GET_MID_TID_LIST_SUCCESS = 'GET_MID_TID_LIST_SUCCESS';
export const GET_MID_TID_LIST_FAILED = 'GET_MID_TID_LIST_FAILED';

export const CLICK_OPEN_LOCK_MODAL = 'CLICK_OPEN_LOCK_MODAL';
export const CLICK_CLOSE_LOCK_MODAL = 'CLICK_CLOSE_LOCK_MODAL';

export const CLICK_OPEN_UN_LOCK_MODAL = 'CLICK_OPEN_UN_LOCK_MODAL';
export const CLICK_CLOSE_UN_LOCK_MODAL = 'CLICK_CLOSE_UN_LOCK_MODAL';

export const CLICK_OPEN_RESET_PASSWORD_MODAL = 'CLICK_OPEN_RESET_PASSWORD_MODAL';
export const CLICK_CLOSE_RESET_PASSWORD_MODAL = 'CLICK_CLOSE_RESET_PASSWORD_MODAL';

export const LOCK_UNLOCK_MID_TID = 'LOCK_UNLOCK_MID_TID';
export const LOCK_UNLOCK_MID_TID_SUCCESS = 'LOCK_UNLOCK_MID_TID_SUCCESS';
export const LOCK_UNLOCK_MID_TID_FAILED = 'LOCK_UNLOCK_MID_TID_FAILED';

export const RESET_PASS_MID_TID = 'RESET_PASS_MID_TID';
export const RESET_PASS_MID_TID_SUCCESS = 'RESET_PASS_MID_TID_SUCCESS';
export const RESET_PASS_MID_TID_FAILED = 'RESET_PASS_MID_TID_FAILED';
