export const GET_ALL_MASTER_MERCHANT = 'GET_ALL_MASTER_MERCHANT';
export const GET_ALL_MASTER_MERCHANT_SUCCESS = 'GET_ALL_MASTER_MERCHANT_SUCCESS';
export const GET_ALL_MASTER_MERCHANT_FAIL = 'GET_ALL_MASTER_MERCHANT_FAIL';

export const GET_ALL_MCC_NATIONAL = 'GET_ALL_MCC_NATIONAL';
export const GET_ALL_MCC_NATIONAL_SUCCESS = 'GET_ALL_MCC_NATIONAL_SUCCESS';
export const GET_ALL_MCC_NATIONAL_FAIL = 'GET_ALL_MCC_NATIONAL_FAIL';

export const GET_ALL_PROVINCE = 'GET_ALL_PROVINCE';
export const GET_ALL_PROVINCE_SUCCESS = 'GET_ALL_PROVINCE_SUCCESS';
export const GET_ALL_PROVINCE_FAIL = 'GET_ALL_PROVINCE_FAIL';

export const GET_ALL_DISTRICT_BY_PROVINCE = 'GET_ALL_DISTRICT_BY_PROVINCE';
export const GET_ALL_DISTRICT_BY_PROVINCE_SUCCESS = 'GET_ALL_DISTRICT_BY_PROVINCE_SUCCESS';
export const GET_ALL_DISTRICT_BY_PROVINCE_FAIL = 'GET_ALL_DISTRICT_BY_PROVINCE_FAIL';

export const GET_ALL_BRANCH_BANK = 'GET_ALL_BRANCH_BANK';
export const GET_ALL_BRANCH_BANK_SUCCESS = 'GET_ALL_BRANCH_BANK_SUCCESS';
export const GET_ALL_BRANCH_BANK_FAIL = 'GET_ALL_BRANCH_BANK_FAIL';

export const GET_ALL_MCC_INTERIOR = 'GET_ALL_MCC_INTERIOR';
export const GET_ALL_MCC_INTERIOR_SUCCESS = 'GET_ALL_MCC_INTERIOR_SUCCESS';
export const GET_ALL_MCC_INTERIOR_FAIL = 'GET_ALL_MCC_INTERIOR_FAIL';

export const GET_ALL_BRANCH_BANK_BY_USER = 'GET_ALL_BRANCH_BANK_BY_USER';
export const GET_ALL_BRANCH_BANK_BY_USER_SUCCESS = 'GET_ALL_BRANCH_BANK_BY_USER_SUCCESS';
export const GET_ALL_BRANCH_BANK_BY_USER_FAIL = 'GET_ALL_BRANCH_BANK_BY_USER_FAIL';

export const GET_ALL_STAFF_BY_DEPARTMENT = 'GET_ALL_STAFF_BY_DEPARTMENT';
export const GET_ALL_STAFF_BY_DEPARTMENT_SUCCESS = 'GET_ALL_STAFF_BY_DEPARTMENT_SUCCESS';
export const GET_ALL_STAFF_BY_DEPARTMENT_FAIL = 'GET_ALL_STAFF_BY_DEPARTMENT_FAIL';

export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL';

export const GET_ALL_BUSINESS_PRODUCT = 'GET_ALL_BUSINESS_PRODUCT';
export const GET_ALL_BUSINESS_PRODUCT_SUCCESS = 'GET_ALL_BUSINESS_PRODUCT_SUCCESS';
export const GET_ALL_BUSINESS_PRODUCT_FAIL = 'GET_ALL_BUSINESS_PRODUCT_FAIL';

export const GET_ALL_BANK = 'GET_ALL_BANK';
export const GET_ALL_BANK_SUCCESS = 'GET_ALL_BANK_SUCCESS';
export const GET_ALL_BANK_FAIL = 'GET_ALL_BANK_FAIL';
