export const GET_ALL_INTERIOR_MMC = 'GET_ALL_INTERIOR_MMC';
export const GET_ALL_INTERIOR_MMC_SUCCESS = 'GET_ALL_INTERIOR_MMC_SUCCESS';
export const GET_ALL_INTERIOR_MMC_FAIL = 'GET_ALL_INTERIOR_MMC_FAIL';

export const LOCK_OR_UNLOCK_INTERIOR_MMC = 'LOCK_OR_UNLOCK_INTERIOR_MMC';
export const LOCK_OR_UNLOCK_INTERIOR_MMC_SUCCESS = 'LOCK_OR_UNLOCK_INTERIOR_MMC_SUCCESS';
export const LOCK_OR_UNLOCK_INTERIOR_MMC_FAIL = 'LOCK_OR_UNLOCK_INTERIOR_MMC_FAIL';

export const CLICK_TO_OPEN_INTERIOR_MCC = 'CLICK_TO_OPEN_INTERIOR_MCC';
export const CLICK_TO_CLOSE_INTERIOR_MCC = 'CLICK_TO_CLOSE_INTERIOR_MCC';

export const CLEAR_LIST_INTERIOR_MCC = 'CLEAR_LIST_INTERIOR_MCC';
// ========= search

export const ADD_INTERIOR_MMC = 'ADD_INTERIOR_MMC';
export const ADD_INTERIOR_MMC_SUCCESS = 'ADD_INTERIOR_MMC_SUCCESS';
export const ADD_INTERIOR_MMC_FAIL = 'ADD_INTERIOR_MMC_FAIL';

export const EDIT_INTERIOR_MMC = 'EDIT_INTERIOR_MMC';
export const EDIT_INTERIOR_MMC_SUCCESS = 'EDIT_INTERIOR_MMC_SUCCESS';
export const EDIT_INTERIOR_MMC_FAIL = 'EDIT_INTERIOR_MMC_FAIL';

export const GET_INTERIOR_MMC = 'GET_INTERIOR_MMC';
export const GET_INTERIOR_MMC_SUCCESS = 'GET_INTERIOR_MMC_SUCCESS';
export const GET_INTERIOR_MMC_FAIL = 'GET_INTERIOR_MMC_FAIL';
