export const GET_ALL_INTERNATIONAL_MMC = 'GET_ALL_INTERNATIONAL_MMC';
export const GET_ALL_INTERNATIONAL_MMC_SUCCESS = 'GET_ALL_INTERNATIONAL_MMC_SUCCESS';
export const GET_ALL_INTERNATIONAL_MMC_FAIL = 'GET_ALL_INTERNATIONAL_MMC_FAIL';

export const LOCK_OR_UNLOCK_INTERNATIONAL_MMC = 'LOCK_OR_UNLOCK_INTERNATIONAL_MMC';
export const LOCK_OR_UNLOCK_INTERNATIONAL_MMC_SUCCESS = 'LOCK_OR_UNLOCK_INTERNATIONAL_MMC_SUCCESS';
export const LOCK_OR_UNLOCK_INTERNATIONAL_MMC_FAIL = 'LOCK_OR_UNLOCK_INTERNATIONAL_MMC_FAIL';

export const CLICK_TO_OPEN_INTERNATIONAL_MCC = 'CLICK_TO_OPEN_INTERNATIONAL_MCC';
export const CLICK_TO_CLOSE_INTERNATIONAL_MCC = 'CLICK_TO_CLOSE_INTERNATIONAL_MCC';

export const CLEAR_LIST_INTERNATIONAL_MCC = 'CLEAR_LIST_INTERNATIONAL_MCC';
// ========= search

export const ADD_INTERNATIONAL_MMC = 'ADD_INTERNATIONAL_MMC';
export const ADD_INTERNATIONAL_MMC_SUCCESS = 'ADD_INTERNATIONAL_MMC_SUCCESS';
export const ADD_INTERNATIONAL_MMC_FAIL = 'ADD_INTERNATIONAL_MMC_FAIL';

export const EDIT_INTERNATIONAL_MMC = 'EDIT_INTERNATIONAL_MMC';
export const EDIT_INTERNATIONAL_MMC_SUCCESS = 'EDIT_INTERNATIONAL_MMC_SUCCESS';
export const EDIT_INTERNATIONAL_MMC_FAIL = 'EDIT_INTERNATIONAL_MMC_FAIL';

export const GET_INTERNATIONAL_MMC = 'GET_INTERNATIONAL_MMC';
export const GET_INTERNATIONAL_MMC_SUCCESS = 'GET_INTERNATIONAL_MMC_SUCCESS';
export const GET_INTERNATIONAL_MMC_FAIL = 'GET_INTERNATIONAL_MMC_FAIL';
