export const GET_ALL_DEPARTMENT = 'GET_ALL_DEPARTMENT';
export const GET_ALL_DEPARTMENT_SUCCESS = 'GET_ALL_DEPARTMENT_SUCCESS';
export const GET_ALL_DEPARTMENT_FAIL = 'GET_ALL_DEPARTMENT_FAIL';

export const LOCK_OR_UNLOCK_DEPARTMENT = 'LOCK_OR_UNLOCK_DEPARTMENT';
export const LOCK_OR_UNLOCK_DEPARTMENT_SUCCESS = 'LOCK_OR_UNLOCK_DEPARTMENT_SUCCESS';
export const LOCK_OR_UNLOCK_DEPARTMENT_FAIL = 'LOCK_OR_UNLOCK_DEPARTMENT_FAIL';

export const CLICK_TO_OPEN_DEPARTMENT = 'CLICK_TO_OPEN_DEPARTMENT';
export const CLICK_TO_CLOSE_DEPARTMENT = 'CLICK_TO_CLOSE_DEPARTMENT';

export const CLEAR_LIST_DEPARTMENT = 'CLEAR_LIST_DEPARTMENT';
// ========= search

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const ADD_DEPARTMENT_SUCCESS = 'ADD_DEPARTMENT_SUCCESS';
export const ADD_DEPARTMENT_FAIL = 'ADD_DEPARTMENT_FAIL';

export const EDIT_DEPARTMENT = 'EDIT_DEPARTMENT';
export const EDIT_DEPARTMENT_SUCCESS = 'EDIT_DEPARTMENT_SUCCESS';
export const EDIT_DEPARTMENT_FAIL = 'EDIT_DEPARTMENT_FAIL';

export const GET_DEPARTMENT = 'GET_DEPARTMENT';
export const GET_DEPARTMENT_SUCCESS = 'GET_DEPARTMENT_SUCCESS';
export const GET_DEPARTMENT_FAIL = 'GET_DEPARTMENT_FAIL';
