export const ADD_TERMINAL = 'ADD_TERMINAL';
export const ADD_TERMINAL_SUCCESS = 'ADD_TERMINAL_SUCCESS';
export const ADD_TERMINAL_FAILED = 'ADD_TERMINAL_FAILED';

export const EDIT_TERMINAL = 'EDIT_TERMINAL';
export const EDIT_TERMINAL_SUCCESS = 'EDIT_TERMINAL_SUCCESS';
export const EDIT_TERMINAL_FAILED = 'EDIT_TERMINAL_FAILED';

export const GET_CACHE_TERMINAL = 'GET_CACHE_TERMINAL';
export const GET_CACHE_TERMINAL_SUCCESS = 'GET_CACHE_TERMINAL_SUCCESS';
export const GET_CACHE_TERMINAL_FAILED = 'GET_CACHE_TERMINAL_FAILED';

export const GET_MERCHANT_LIST = 'GET_MERCHANT_LIST';
export const GET_MERCHANT_LIST_SUCCESS = 'GET_MERCHANT_LIST_SUCCESS';
export const GET_MERCHANT_LIST_FAILED = 'GET_MERCHANT_LIST_FAILED';

export const GET_MERCHANT_BRANCH = 'GET_MERCHANT_BRANCH';
export const GET_MERCHANT_BRANCH_SUCCESS = 'GET_MERCHANT_BRANCH_SUCCESS';
export const GET_MERCHANT_BRANCH_FAILED = 'GET_MERCHANT_BRANCH_FAILED';

export const GET_TERMINAL_PLACE = 'GET_TERMINAL_PLACE';
export const GET_TERMINAL_PLACE_SUCCESS = 'GET_TERMINAL_PLACE_SUCCESS';
export const GET_TERMINAL_PLACE_FAILED = 'GET_TERMINAL_PLACE_FAILED';

export const GET_TERMINAL_DETAIL = 'GET_TERMINAL_DETAIL';
export const GET_TERMINAL_DETAIL_SUCCESS = 'GET_TERMINAL_DETAIL_SUCCESS';
export const GET_TERMINAL_DETAIL_FAILED = 'GET_TERMINAL_DETAIL_FAILED';

export const GET_TERMINAL_LIST = 'GET_TERMINAL_LIST';
export const GET_TERMINAL_LIST_SUCCESS = 'GET_TERMINAL_LIST_SUCCESS';
export const GET_TERMINAL_LIST_FAILED = 'GET_TERMINAL_LIST_FAILED';

export const GET_TERMINAL_LIST_DENIED = 'GET_TERMINAL_LIST_DENIED';
export const GET_TERMINAL_LIST_DENIED_SUCCESS = 'GET_TERMINAL_LIST_DENIED_SUCCESS';
export const GET_TERMINAL_LIST_DENIED_FAILED = 'GET_TERMINAL_LIST_DENIED_FAILED';

export const SET_LEVEL_TERMINAL = 'SET_LEVEL_TERMINAL';

export const GET_TERMINAL_DETAIL_DENIED = 'GET_TERMINAL_DETAIL_DENIED';
export const GET_TERMINAL_DETAIL_DENIED_SUCCESS = 'GET_TERMINAL_DETAIL_DENIED_SUCCESS';
export const GET_TERMINAL_DETAIL_DENIED_FAILED = 'GET_TERMINAL_DETAIL_DENIED_FAILED';

export const APPROVED_TERMINAL = 'APPROVED_TERMINAL';
export const APPROVED_TERMINAL_SUCCESS = 'APPROVED_TERMINAL_SUCCESS';
export const APPROVED_TERMINAL_FAILED = 'APPROVED_TERMINAL_FAILED';

export const DENIED_TERMINAL = 'DENIED_TERMINAL';
export const DENIED_TERMINAL_SUCCESS = 'DENIED_TERMINAL_SUCCESS';
export const DENIED_TERMINAL_FAILED = 'DENIED_TERMINAL_FAILED';

export const CLICK_OPEN_LOCK_MODAL = 'CLICK_OPEN_LOCK_MODAL';
export const CLICK_CLOSE_LOCK_MODAL = 'CLICK_CLOSE_LOCK_MODAL';

export const CLICK_OPEN_UN_LOCK_MODAL = 'CLICK_OPEN_UN_LOCK_MODAL';
export const CLICK_CLOSE_UN_LOCK_MODAL = 'CLICK_CLOSE_UN_LOCK_MODAL';

export const LOCK_UNLOCK_TERMINAL = 'LOCK_UNLOCK_TERMINAL';
export const LOCK_UNLOCK_TERMINAL_SUCCESS = 'LOCK_UNLOCK_TERMINAL_SUCCESS';
export const LOCK_UNLOCK_TERMINAL_FAILED = 'LOCK_UNLOCK_TERMINAL_FAILED';

export const GET_TERMINAL_CODE_NAME = 'GET_TERMINAL_CODE_NAME';
export const GET_TERMINAL_CODE_NAME_SUCCESS = 'GET_TERMINAL_CODE_NAME_SUCCESS';
export const GET_TERMINAL_CODE_NAME_FAILED = 'GET_TERMINAL_CODE_NAME_FAILED';

export const EXPORT_EXCEL_FILE_TERMINAL = 'EXPORT_EXCEL_FILE_TERMINAL';
export const EXPORT_EXCEL_FILE_TERMINAL_SUCCESS = 'EXPORT_EXCEL_FILE_TERMINAL_SUCCESS';
export const EXPORT_EXCEL_FILE_TERMINAL_FAILED = 'EXPORT_EXCEL_FILE_TERMINAL_FAILED';
