export const GET_ALL_GROUP_ROLE = 'GET_ALL_GROUP_ROLE';

export const GET_ALL_GROUP_ROLE_SUCCESS = 'GET_ALL_GROUP_ROLE_SUCCESS';

export const GET_ALL_GROUP_ROLE_FAIL = 'GET_ALL_GROUP_ROLE_FAIL';

export const GET_ALL_BRANCH_BANK_BY_LOCAL_USER = 'GET_ALL_BRANCH_BANK_BY_LOCAL_USER';

export const GET_ALL_BRANCH_BANK_BY_LOCAL_USER_SUCCESS = 'GET_ALL_BRANCH_BANK_BY_LOCAL_USER_SUCCESS';

export const GET_ALL_BRANCH_BANK_BY_LOCAL_USER_FAIL = 'GET_ALL_BRANCH_BANK_BY_LOCAL_USER_FAIL';

export const GET__DATA_LIST_PAGE = 'GET__DATA_LIST_PAGE';

export const GET__DATA_LIST_PAGE_SUCCESS = 'GET__DATA_LIST_PAGE_SUCCESS';

export const GET__DATA_LIST_PAGE_FAIL = 'GET__DATA_LIST_PAGE_FAIL';

export const CLICK_TO_OPEN_MODAL_CHANGE_STATUS_LOCAL_ACCOUNT = 'CLICK_TO_OPEN_MODAL_CHANGE_STATUS_LOCAL_ACCOUNT';

export const CLICK_TO_CLOSE_MODAL_CHANGE_STATUS_LOCAL_ACCOUNT = 'CLICK_TO_CLOSE_MODAL_CHANGE_STATUS_LOCAL_ACCOUNT';

export const CHANGE_STATUS_LOCAL_ACCOUNT = 'CHANGE_STATUS_LOCAL_ACCOUNT';

export const CHANGE_STATUS_LOCAL_ACCOUNT_SUCCESS = 'CHANGE_STATUS_LOCAL_ACCOUNT_SUCCESS';

export const CHANGE_STATUS_LOCAL_ACCOUNT_FAIL = 'CHANGE_STATUS_LOCAL_ACCOUNT_FAIL';

