export const RESET_PASSWORD_LOCAL_ACC = 'RESET_PASSWORD_LOCAL_ACC';

export const RESET_PASSWORD_LOCAL_ACC_SUCCESS = 'RESET_PASSWORD_LOCAL_ACC_SUCCESS';

export const RESET_PASSWORD_LOCAL_ACC_FAIL = 'RESET_PASSWORD_LOCAL_ACC_FAIL';
