export const GET_LOCAL_USER_DATA_BY_ID = 'GET_LOCAL_USER_DATA_BY_ID';

export const GET_LOCAL_USER_DATA_BY_ID_SUCCESS = 'GET_LOCAL_USER_DATA_BY_ID_SUCCESS';

export const GET_LOCAL_USER_DATA_BY_ID_FAIL = 'GET_LOCAL_USER_DATA_BY_ID_FAIL';


export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';

export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL';
