export const GET_ALL_FUNCTION = 'GET_ALL_FUNCTION';

export const GET_ALL_FUNCTION_SUCCESS = 'GET_ALL_FUNCTION_SUCCESS';

export const GET_ALL_FUNCTION_FAIL = 'GET_ALL_FUNCTION_FAIL';

export const GET_GROUP_DETAIL_ROLES = 'GET_GROUP_DETAIL';

export const GET_GROUP_DETAIL_ROLES_SUCCESS = 'GET_GROUP_DETAIL_SUCCESS';

export const GET_GROUP_DETAIL_ROLES_FAIL = 'GET_GROUP_DETAIL_FAIL';



