export const GET_LIST_ROLE = 'GET_LIST_ROLE';

export const GET_LIST_ROLE_SUCCESS = 'GET_LIST_ROLE_SUCCESS';

export const GET_LIST_ROLE_FAIL = 'GET_LIST_ROLE_FAIL';

export const CLICK_TO_OPEN_CHANGE_STATUS_MODAL_ROLE = 'CLICK_TO_OPEN_CHANGE_STATUS_MODAL_ROLE';

export const CLICK_TO_CLOSE_CHANGE_STATUS_MODAL_ROLE = 'CLICK_TO_CLOSE_CHANGE_STATUS_MODAL_ROLE';

export const CHANGE_STATUS_ROLE = 'CHANGE_STATUS_ROLE';

export const CHANGE_STATUS_ROLE_SUCCESS = 'CHANGE_STATUS_ROLE_SUCCESS';

export const CHANGE_STATUS_ROLE_FAIL = 'CHANGE_STATUS_ROLE_FAIL';
