export const GET_DETAIL_TRANSACTION_MAKED = 'GET_DETAIL_TRANSACTION_MAKED';
export const GET_DETAIL_TRANSACTION_MAKED_SUCCESS = 'GET_DETAIL_TRANSACTION_MAKED_SUCCESS';
export const GET_DETAIL_TRANSACTION_MAKED_FAILED = 'GET_DETAIL_TRANSACTION_MAKED_FAILED';

export const EXPORT_EXCEL_FILE_REPORT = 'EXPORT_EXCEL_FILE_REPORT';
export const EXPORT_EXCEL_FILE_REPORT_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_FAILED = 'EXPORT_EXCEL_FILE_REPORT_FAILED';

export const GET_LIST_TRANSACTION_FAIL = 'GET_LIST_TRANSACTION_FAIL';
export const GET_LIST_TRANSACTION_FAIL_SUCCESS = 'GET_LIST_TRANSACTION_FAIL_SUCCESS';
export const GET_LIST_TRANSACTION_FAIL_FAILED = 'GET_LIST_TRANSACTION_FAIL_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_ERROR = 'EXPORT_EXCEL_FILE_REPORT_ERROR';
export const EXPORT_EXCEL_FILE_REPORT_ERROR_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_ERROR_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_ERROR_FAILED = 'EXPORT_EXCEL_FILE_REPORT_ERROR_FAILED';


export const GET_LIST_TRANSACTION_INTERNATIONAL_MCC = 'GET_LIST_TRANSACTION_INTERNATIONAL_MCC';
export const GET_LIST_TRANSACTION_INTERNATIONAL_MCC_SUCCESS = 'GET_LIST_TRANSACTION_INTERNATIONAL_MCC_SUCCESS';
export const GET_LIST_TRANSACTION_INTERNATIONAL_MCC_FAILED = 'GET_LIST_TRANSACTION_INTERNATIONAL_MCC_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_INTER_MCC = 'EXPORT_EXCEL_FILE_REPORT_INTER_MCC';
export const EXPORT_EXCEL_FILE_REPORT_INTER_MCC_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_INTER_MCC_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_INTER_MCC_FAILED = 'EXPORT_EXCEL_FILE_REPORT_INTER_MCC_FAILED';

export const GET_LIST_TRANSACTION_MMC = 'GET_LIST_TRANSACTION_MMC';
export const GET_LIST_TRANSACTION_MMC_SUCCESS = 'GET_LIST_TRANSACTION_MMC_SUCCESS';
export const GET_LIST_TRANSACTION_MMC_FAILED = 'GET_LIST_TRANSACTION_MMC_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_MMC = 'EXPORT_EXCEL_FILE_REPORT_MMC';
export const EXPORT_EXCEL_FILE_REPORT_MMC_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_MMC_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_MMC_FAILED = 'EXPORT_EXCEL_FILE_REPORT_MMC_FAILED';

export const GET_LIST_TRANSACTION_REFUND = 'GET_LIST_TRANSACTION_REFUND';
export const GET_LIST_TRANSACTION_REFUND_SUCCESS = 'GET_LIST_TRANSACTION_REFUND_SUCCESS';
export const GET_LIST_TRANSACTION_REFUND_FAILED = 'GET_LIST_TRANSACTION_REFUND_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_REFUND = 'EXPORT_EXCEL_FILE_REPORT_REFUND';
export const EXPORT_EXCEL_FILE_REPORT_REFUND_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_REFUND_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_REFUND_FAILED = 'EXPORT_EXCEL_FILE_REPORT_REFUND_FAILED';

export const GET_LIST_TRANSACTION_MERCHANT = 'GET_LIST_TRANSACTION_MERCHANT';
export const GET_LIST_TRANSACTION_MERCHANT_SUCCESS = 'GET_LIST_TRANSACTION_MERCHANT_SUCCESS';
export const GET_LIST_TRANSACTION_MERCHANT_FAILED = 'GET_LIST_TRANSACTION_MERCHANT_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_MERCHANT = 'EXPORT_EXCEL_FILE_REPORT_MERCHANT';
export const EXPORT_EXCEL_FILE_REPORT_MERCHANT_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_MERCHANT_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_MERCHANT_FAILED = 'EXPORT_EXCEL_FILE_REPORT_MERCHANT_FAILED';

export const GET_LIST_TRANSACTION_MERCHANT_BRANCH = 'GET_LIST_TRANSACTION_MERCHANT_BRANCH';
export const GET_LIST_TRANSACTION_MERCHANT_BRANCH_SUCCESS = 'GET_LIST_TRANSACTION_MERCHANT_BRANCH_SUCCESS';
export const GET_LIST_TRANSACTION_MERCHANT_BRANCH_FAILED = 'GET_LIST_TRANSACTION_MERCHANT_BRANCH_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_MERCHANT_BRANCH = 'EXPORT_EXCEL_FILE_REPORT_MERCHANT_BRANCH';
export const EXPORT_EXCEL_FILE_REPORT_MERCHANT_BRANCH_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_MERCHANT_BRANCH_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_MERCHANT_BRANCH_FAILED = 'EXPORT_EXCEL_FILE_REPORT_MERCHANT_BRANCH_FAILED';

export const GET_LIST_TRANSACTION_TERMINAL = 'GET_LIST_TRANSACTION_TERMINAL';
export const GET_LIST_TRANSACTION_TERMINAL_SUCCESS = 'GET_LIST_TRANSACTION_TERMINAL_SUCCESS';
export const GET_LIST_TRANSACTION_TERMINAL_FAILED = 'GET_LIST_TRANSACTION_TERMINAL_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_TERMINAL = 'EXPORT_EXCEL_FILE_REPORT_TERMINAL';
export const EXPORT_EXCEL_FILE_REPORT_TERMINAL_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_TERMINAL_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_TERMINAL_FAILED = 'EXPORT_EXCEL_FILE_REPORT_TERMINAL_FAILED';

export const GET_DETAIL_TRAN_BUSINESS_MAKED = 'GET_DETAIL_TRAN_BUSINESS_MAKED';
export const GET_DETAIL_TRAN_BUSINESS_MAKED_SUCCESS = 'GET_DETAIL_TRAN_BUSINESS_MAKED_SUCCESS';
export const GET_DETAIL_TRAN_BUSINESS_MAKED_FAILED = 'GET_DETAIL_TRAN_BUSINESS_MAKED_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_BUSINESS = 'EXPORT_EXCEL_FILE_REPORT_BUSINESS';
export const EXPORT_EXCEL_FILE_REPORT_BUSINESS_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_BUSINESS_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_BUSINESS_FAILED = 'EXPORT_EXCEL_FILE_REPORT_BUSINESS_FAILED';

export const GET_DETAIL_TRANSACTION_UPDATE = 'GET_DETAIL_TRANSACTION_UPDATE';
export const GET_DETAIL_TRANSACTION_UPDATE_SUCCESS = 'GET_DETAIL_TRANSACTION_UPDATE_SUCCESS';
export const GET_DETAIL_TRANSACTION_UPDATE_FAILED = 'GET_DETAIL_TRANSACTION_UPDATE_FAILED';

export const EXPORT_EXCEL_FILE_REPORT_UPDATE = 'EXPORT_EXCEL_FILE_REPORT_UPDATE';
export const EXPORT_EXCEL_FILE_REPORT_UPDATE_SUCCESS = 'EXPORT_EXCEL_FILE_REPORT_UPDATE_SUCCESS';
export const EXPORT_EXCEL_FILE_REPORT_UPDATE_FAILED = 'EXPORT_EXCEL_FILE_REPORT_UPDATE_FAILED';
