export const ADD_QRCODE = 'ADD_QRCODE';
export const ADD_QRCODE_SUCCESS = 'ADD_QRCODE_SUCCESS';
export const ADD_QRCODE_FAILED = 'ADD_QRCODE_FAILED';

export const EDIT_QRCODE = 'EDIT_QRCODE';
export const EDIT_QRCODE_SUCCESS = 'EDIT_QRCODE_SUCCESS';
export const EDIT_QRCODE_FAILED = 'EDIT_QRCODE_FAILED';

export const GET_QRCODE = 'GET_QRCODE';
export const GET_QRCODE_SUCCESS = 'GET_QRCODE_SUCCESS';
export const GET_QRCODE_FAILED = 'GET_QRCODE_FAILED';

export const GET_QRCODE_LIST = 'GET_QRCODE_LIST';
export const GET_QRCODE_LIST_SUCCESS = 'GET_QRCODE_LIST_SUCCESS';
export const GET_QRCODE_LIST_FAILED = 'GET_QRCODE_LIST_FAILED';

export const CLICK_OPEN_LOCK_MODAL = 'CLICK_OPEN_LOCK_MODAL';
export const CLICK_CLOSE_LOCK_MODAL = 'CLICK_CLOSE_LOCK_MODAL';

export const CLICK_OPEN_UN_LOCK_MODAL = 'CLICK_OPEN_UN_LOCK_MODAL';
export const CLICK_CLOSE_UN_LOCK_MODAL = 'CLICK_CLOSE_UN_LOCK_MODAL';

export const LOCK_UNLOCK_QRCODE = 'LOCK_UNLOCK_QRCODE';
export const LOCK_UNLOCK_QRCODE_SUCCESS = 'LOCK_UNLOCK_QRCODE_SUCCESS';
export const LOCK_UNLOCK_QRCODE_FAILED = 'LOCK_UNLOCK_QRCODE_FAILED';
