export const GET_ACC_PERSONAL_INFO = 'GET_ACC_PERSONAL_INFO';

export const GET_ACC_PERSONAL_INFO_SUCCESS = 'GET_ACC_PERSONAL_INFO_SUCCESS';

export const GET_ACC_PERSONAL_INFO_FAIL = 'GET_ACC_PERSONAL_INFO_FAIL';


export const UPDATE_ACC_INFO = 'UPDATE_ACC_INFO';

export const UPDATE_ACC_INFO_SUCCESS = 'UPDATE_ACC_INFO_SUCCESS';

export const UPDATE_ACC_INFO_FAIL = 'UPDATE_ACC_INFO_FAIL';

export const ACC_CHANGE_PASSWORD = 'ACC_CHANGE_PASSWORD';

export const ACC_CHANGE_PASSWORD_SUCCESS = 'ACC_CHANGE_PASSWORD_SUCCESS';

export const ACC_CHANGE_PASSWORD_FAIL = 'ACC_CHANGE_PASSWORD_FAIL';


